# Travis CI configuration file.

sudo: required

language: node_js
node_js: stable

addons:
  chrome: stable

stages:
  - compile
  - test
  - name: deploy
    if: branch = master AND NOT type = pull_request

jobs:
  include:

    - stage: compile
      script:
        - npx npm-install-peers
        - yarn build

    - stage: test
      script:
        - yarn lint
        - yarn test
        # - yarn e2e

    - stage: deploy
      if: branch = master
      script:
        - yarn deploy:demo
